### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by DonatoReis** [neex/http2smugl#15]
@cyal1 @neex 

Need to update how to install the tool.

**Comment by CaroGross** [comment]
Hey everyone, I also cannot get http2smugl to install.

System is MacOS 12.3.1.

Tried with multiple versions of go (1.16, 1.17, 1.18). Somehow I always seem to have a problem with the go version and quic.
Any idea what I could do to fix this?

Thank you for the effort!


**Go v16: Quic needs later go version**

```
go version
go version go1.16.15 darwin/amd64


go get -u github.com/neex/http2smugl
# github.com/neex/http2smugl
/Users/name/go/pkg/mod/github.com/neex/http2smugl@v0.0.0-20211110095419-acff4825c069/http3.go:191:27: undefined: quic.Session
note: module requires Go 1.17
```

**Go 1.17: go get deprecated, tried with go install, got error about quic.session**

```
brew link --force go@1.17
Linking /usr/local/Cellar/go@1.17/1.17.10... 2 symlinks created.


go get github.com/neex/http2smugl
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/onsi/ginkgo v1.16.4
go: downloading github.com/marten-seemann/qtls-go1-16 v0.1.4
go: downloading golang.org/x/tools v0.1.2
go: downloading github.com/go-task/slim-sprig v0.0.0-20210107165309-348f09dbbbc0
go: downloading github.com/nxadm/tail v1.4.8
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading golang.org/x/mod v0.4.2
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.



go get -u github.com/neex/http2smugl
go: downloading golang.org/x/net v0.0.0-20220524220425-1d687d428aca
go: downloading github.com/spf13/cobra v1.4.0
go: downloading github.com/lucas-clemente/quic-go v0.27.1
go: downloading golang.org/x/text v0.3.7
go: downloading golang.org/x/sys v0.0.0-20220520151302-bc2c85ada10a
go: downloading golang.org/x/crypto v0.0.0-20220518034528-6f7dac969898
go: downloading github.com/onsi/ginkgo v1.16.5
go: downloading github.com/marten-seemann/qtls-go1-17 v0.1.1
go: downloading golang.org/x/tools v0.1.10
go: downloading github.com/marten-seemann/qtls-go1-16 v0.1.5
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading golang.org/x/mod v0.5.1
go: downloading golang.org/x/xerrors v0.0.0-20220517211312-f3a8303e98df
go: downloading github.com/marten-seemann/qtls-go1-18 v0.1.1
go: downloading golang.org/x/mod v0.6.0-dev.0.20220106191415-9b9b3d81d5e3
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
# github.com/neex/http2smugl
/Users/name/go/pkg/mod/github.com/neex/http2smugl@v0.0.0-20211110095419-acff4825c069/http3.go:191:27: undefined: quic.Session
```



**Go v.18: quic-go doesn't build on Go 1.18 yet**

```
go get github.com/neex/http2smugl
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

go install github.com/neex/http2smugl@latest
go: downloading github.com/neex/http2smugl v0.0.0-20211110095419-acff4825c069
go: downloading golang.org/x/net v0.0.0-20211104170005-ce137452f963
go: downloading github.com/spf13/cobra v1.2.1
go: downloading github.com/lucas-clemente/quic-go v0.24.0
go: downloading github.com/marten-seemann/qpack v0.2.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/cheekybits/genny v1.0.0
go: downloading golang.org/x/sys v0.0.0-20210510120138-977fb7262007
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/marten-seemann/qtls-go1-17 v0.1.0
# github.com/lucas-clemente/quic-go/internal/qtls
/Users/name/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
```

**Comment by Gamithra** [comment]
Similar issues here:
```
~/tools$ go get github.com/neex/http2smugl
# github.com/neex/http2smugl
../go/src/github.com/neex/http2smugl/http3.go:65:4: unknown field 'KeepAlive' in struct literal of type quic.Config
../go/src/github.com/neex/http2smugl/http3.go:191:32: undefined: quic.Session
```

```
~/tools$ go version
go version go1.18.3 linux/amd64
```

**Comment by hx01freak** [comment]
@neex same issue for me too...can u solve this issue plz.

undefined: quic.Session.
